
import 'package:get/get.dart';
// from the device language

class  mylocale implements Translations {
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "Language": "اللغة",
      "home": "الصفحة الرئيسية",
      "Services": "الخدمات",
      "personal Page": "الصفحة الشخصية",
      "About": "الخصائص",
      "Love Your Soul": "اعتني بنفسك",
      "we pour love and care in every patient": "نحن نبذل الجهد والرعاية لكل المرضي ",
      "we make you never lose hope": "لن نجعلك تفقد الامل ابدا",
      "Top Ordered ": "الاعلي ترتيبا",
      " patient every day ": "عدد المرضي اليومي ",
      " Experience Nurses ":" الممرضين الخبراء ",
      " Patient Capacity ":" عدد المرضي الكلي  " ,
      " Years Experience ":"سنوات الخبرة ",
      "Our job is to make you comfortable and save your life":"مهمتنا ان نجعلك مرتاحا والحفاظ علي حياتك ",
      "Pediatric Nursing": " رعاية الأطفال",
          "Elderly Nursing": " رعاية المسنين",
          "Special Care" : "رعاية خاصة",
          "Emergency Nursing" :"    تمريض الطوارئ" ,
          "Woman Nursing": "رعاية النساء",
          "Psychiatric Nursing" : "التمريض النفسي",
      "All":"الكل " ,
      "Male":"الرجال",
      "Female":"النساء",
      "Location":"الموقع" ,
      "Price":"السعر" ,
      "Active":"النشطاء" ,
      'Country':'الدولة',
      'My profile ':'حسابي الشخصي ',
      "English":"الانجليزية",
      "Arabic":"العربية",
      'Privacy policy':'خصوصية الامان',
      'Dark mode':'الوضع الداكن',
      'Settings':"الاعدادات",


      "12": "ادخل البريد الالكتروني",
      "13": "ادخل كلمة المرور",
      "14": "هل نسيت كلمة المرور",
      "15": "تسجيل الدخول",
      "16": "ليس لديك حساب ? ",
      "17": "انشاء حساب",
      "18": "البريد الالكتروني",
      "19": "كلمة المرور",
      "20": "اسم المستخدم",
      "21": "رقم الهاتف",
      "22": "ادخل رقم الهاتف",
      "23": "ادخل اسم المستخدم",
      "24":
      "انشاء حساب من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
      "25": " لديك حساب ? ",
      "26": "تسجيل الدخول",
      "27": "فحص البريد الالكتروني",
      "28": "تم انشاء الحساب بنجاح",
      "29": "الرجاء ادخال البريد لتلقي رمز التحقق",
      "30": "فحص",
      "31": "الذهاب لتسجيل الدخول",
      "32": "نجاح",
      "33": "حفظ",
      "34": "الرجاء ادخال كلمة المرور الجديدة",
      "35": "الكلمة الجديدة",
      "36": "تم اعادة تعيين كلمة المرور بنجاح",
      "37": "تهانينا",
      "38": "تم التسجيل بنجاح"
    },
    "en": {

      "Language": "Language",
      "home": "home",
      "Services": "Services",
      "personal Page": "personal Page",
      "About": "About",
      "Love Your Soul": "Love Your Soul",
      "we pour love and care in every patient": "we pour love and care in every patient.",
      "we make you never lose hope": "we make you never lose hope",
      "Top Ordered ":"Top Ordered ",
      " patient every day ": " patient every day",
      " Experience Nurses ":" Experience Nurses ",
      " Patient Capacity ":" Patient Capacity " ,
      " Years Experience ":" Years Experience ",
      "Our job is to make you comfortable and save your life":"Our job is to make you comfortable and save your life",
      "Pediatric Nursing": "Pediatric Nursing",
          "Elderly Nursing":"Elderly Nursing",
          "Special Care":"Special Care",
          "Emergency Nursing":"Emergency Nursing",
          "Woman Nursing":"Woman Nursing",
          "Psychiatric Nursing":"Psychiatric Nursing",
  "All":"All",
"Male":"Male",
  "Female":"Female",
  "Location":"Location" ,
  "Price":"Price" ,
   "Active":"Active",
      'Settings':'Settings',
      'Country':'Country',
      'My profile ':'My profile ',
      "English":"English",
      "Arabic":"Arabic",
      'Privacy policy':'Privacy policy',
      'Dark mode':'Dark mode',
      'Settings':'Settings',


      "12": "Enter Your Email",
      "13": "Enter Your Password",
      "14": "Forget Password",
      "15": "Sign In",
      "16": "Dont Have An Account ? ",
      "17": "Sign Up",
      "18": "Email",
      "19": "Password",
      "20": "Username",
      "21": "Phone",
      "22": "Enter Your Phone",
      "23": "Enter Your Username",
      "24":
      "Sign Up With Your Email And Password OR Continue With Social Media",
      "25": " have an account ? ",
      "26": "SignIn",
      "27": "Check Email",
      "28": "Account successfully created",
      "29": "please Enter Your Email Address To Recive A verification code",
      "30": "check",
      "31": "Go To Login",
      "32": "Success",
      "33": "save",
      "34": "Please Enter new Password",
      "35": "New Password",
      "36": "Password has been reset successfully",
      "37": "congratulations",
      "38": "successfully registered"
    }
  };
}
